### ISSUE TITLE
Crashing macOS Big Sur

### ISSUE THREAD

**Issue by pmac** [mozilla-iam/sso-no-phishing#12]
I know this sounds crazy but it seems that this addon is causing my machine to kernel panic after upgrading to Big Sur (macOS 11.0.1). I have tried a fresh Firefox profile and it doesn't happen, but then it immediately crashed when I reinstalled this addon. I've been poking around in the code and I have no idea what could be causing this. If anyone has a maching running Big Sur it would be a big help just to reproduce this so that we could be sure that it's really this and not something else unique to my machine. I have reproduced it with Firefox Dev Edition 84.0b2 and Release 83.0.

**Comment by floatingatoll** [comment]
Are you still able to reproduce this crash on a more recent Big Sur?

**Comment by pmac** [comment]
Ah! No I am not. This was resolved by a macOS update. I also [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1678428) about this after some internal discussion and failed to follow up here. The bug has been closed and this can be as well. Thanks for the reminder.
