### ISSUE TITLE
Green does not clear on redirect

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-iam/sso-no-phishing#3]
* If you are already logged in the green persists
* I am using Firefox Nightly 69 on Windows

**Comment by gdestuynder** [comment]
@kbrosnan what version of the addon were you using? (i.e. was it before 1.1.7?)

**Comment by kbrosnan** [comment]
I don't know. I uninstalled it because of this behavior. I assume so as I filed this a day after that release and I was only using it for a short time.

**Comment by gdestuynder** [comment]
@kbrosnan ok, I assume this has been fixed, but if you get the chance to test it again let me know!
and thanks :)

**Comment by kbrosnan** [comment]
Yes looks good with the new version.
